blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

blog_admin:
    resource: "@BlogBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin/

app:
    resource: '@AppBundle/Controller/'
    type: annotation
