BlogBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '255'
        slug:
            type: string
            length: '255'
            unique: true
        body:
            type: text
    lifecycleCallbacks: {  }
